name: despliegue-bo
on: [push]
jobs:
	build:
		runs-on: ubuntu-latest
		steps:
      - uses: actions/checkout@v3
      - name: Modified files
        id: changed-files
        run: |
          echo "changed_files=$(git diff --name-only -r HEAD^1 HEAD | xargs)" >> $GITHUB_OUTPUT
      - name: FTP Deployer
        uses: sand4rt/ftp-deployer@v1.7
        with:
          sftp: false
          host: ${{ secrets.HOST_NAME }}
          port: 21
          username: ${{ secrets.USER_NAME }}
          password: ${{ secrets.PASSWORD }}
          remote_folder: ${{ secrets.REMOTE_FOLDER }} # optional, remote path of your FTP server
          local_folder: tandem # optional, local path, default is: dist
          cleanup: false # optional, remove existing files inside FTP remote folder
          include: '[]' # optional, e.g. '['dist']'
          exclude: '[]' # optional, e.g. '['node_modules/**', '.git/**', '*.env']'
          passive: true # optional