name: despliegue-bo
on:
    push:
        branches: [ main ]
jobs:
    changedfiles:
        runs-on: ubuntu-latest
        outputs:
            src: ${{ steps.changes.outputs.src}}
            dic: ${{ steps.changes.outputs.dic }}
            lbr: ${{ steps.changes.outputs.lbr }}
        steps:
            - name: Get Latest Code
              uses: actions/checkout@v3
            - name: Get changed files
              id: changes
              run: |
                 echo "::set-output name=src::$(git diff --name-only --diff-filter=ACMRT | grep SR* | xargs)"
                 echo "::set-output name=dic::$(git diff --name-only --diff-filter=ACMRT | grep DI* | xargs)"
                 echo "::set-output name=lbr::$(git diff --name-only --diff-filter=ACMRT | grep LM* | xargs)"
            - name: List changed files
              run: |
                 echo ${{changedfiles.outputs.src}}
                 echo ${{changedfiles.outputs.dic}}
                 echo ${{changedfiles.outputs.frm}}
    build:
        runs-on: ubuntu-latest
        needs: changedfiles
        steps:
        - name: Get Latest Code
          uses: actions/checkout@v3
        - name: FTP Deployer
          uses: kevinpainchaud/simple-ftp-deploy-action@v1.2.1
          with:
            ftp_host: ${{ secrets.HOST_NAME }}
            ftp_username: ${{ secrets.USER_NAME }}
            ftp_password: ${{ secrets.PASSWORD }}
            local_source_dir: "tandem"
            dist_target_dir: "tandem"
            delete: "false"
