name: despliegue-bo # Nombre del Workflow
on:
    push:
        branches: [ main ] # El workflow se ejecutar치 cuando se realice un push a la rama main
jobs:
    changedfiles: # Nombre del job
        runs-on: ubuntu-latest # Los steps siguientes se ejecutar치n sobre la ultima versi칩n de Ubuntu
        steps:
            - name: Get Latest Code # Nombre del primer step
              uses: actions/checkout@v3 # Se realiza un checkuot del repositorio
            - uses: yumemi-inc/changed-files@v3 # Este action se usar치 para extraer el nombre de los archivos modificados, agregados etc
              id: changed_src # id del step
              with: # Se agrega como parametro un patron para validar si hay archivos SR modificados
                patterns: |
                    **/SR*
            - run: |
                for file in ${{ steps.changed_src.outputs.files }}; do
                  # do somethihg..
                  echo "$file"
                done
            - uses: yumemi-inc/changed-files@v3
              id: changed_dic
              with: # Se agrega como parametro un patron para validar si hay archivos DI modificados
                patterns: |
                    **/DI*
            - run: |
                for file in ${{ steps.changed_dic.outputs.files }}; do
                  # do somethihg..
                  echo "$file"
                done
            - uses: yumemi-inc/changed-files@v3
              id: changed_lbr
              with: # Se agrega como parametro un patron para validar si hay archivos LM modificados
                patterns: |
                    **/LM*
            - run: |
                for file in ${{ steps.changed_lbr.outputs.files }}; do
                  # do somethihg..
                  echo "$file"
                done
            - name: put_src # Nombre del step para transferir archivos SR
              if: ${{steps.changed_src.outputs.files}} # Si existen archivos modificados sigue el flujo de este step
              uses: kevinpainchaud/simple-ftp-deploy-action@v1.2.1 # Action para transferir archivos via FTP
              with:
                ftp_host: ${{ secrets.HOST_NAME }}
                ftp_username: ${{ secrets.USER_NAME }}
                ftp_password: ${{ secrets.PASSWORD }}
                local_source_dir: "tandem/SRC"
                dist_target_dir: "tandem/SRC"
                delete: "false"
            - name: put_dic # Nombre del step para transferir archivos DI
              if: ${{steps.changed_dic.outputs.files}} # Si existen archivos modificados sigue el flujo de este step
              uses: kevinpainchaud/simple-ftp-deploy-action@v1.2.1 # Action para transferir archivos via FTP
              with:
                ftp_host: ${{ secrets.HOST_NAME }}
                ftp_username: ${{ secrets.USER_NAME }}
                ftp_password: ${{ secrets.PASSWORD }}
                local_source_dir: "tandem/DIC"
                dist_target_dir: "tandem/DIC"
                delete: "false"
            - name: put_lbr # # Nombre del step para transferir archivos LM
              if: ${{steps.changed_lbr.outputs.files}} # Si existen archivos modificados sigue el flujo de este step
              uses: kevinpainchaud/simple-ftp-deploy-action@v1.2.1 # Action para transferir archivos via FTP
              with:
                ftp_host: ${{ secrets.HOST_NAME }}
                ftp_username: ${{ secrets.USER_NAME }}
                ftp_password: ${{ secrets.PASSWORD }}
                local_source_dir: "tandem/LBR"
                dist_target_dir: "tandem/LBR"
                delete: "false"