name: despliegue-bo
on:
    push:
        branches: [ main ]
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
        - name: Get Latest Code
          uses: actions/checkout@v3
        - name: FTP Deployer
          uses: airvzxf/ftp-deployment-action@latest
          with:
            server: ${{ secrets.ftp.HOST_NAME }}
            user: ${{ secrets.ftp.USER_NAME }}
            password: ${{ secrets.ftp.PASSWORD }}
            remote_dir: "/tandem/"
            local_dir: "./tandem"
