name: despliegue-bo
on:
    push:
        branches: [ main ]
jobs:
    changedfiles:
        runs-on: ubuntu-latest
        steps:
            - name: Get Latest Code
              uses: actions/checkout@v3
            - uses: yumemi-inc/changed-files@v3
              id: changed_src
              with:
                patterns: |
                    **/SR*
            - run: |
                for file in ${{ steps.changed_src.outputs.files }}; do
                  # do somethihg..
                  echo "$file"
                done
            - uses: yumemi-inc/changed-files@v3
              id: changed_dic
              with:
                patterns: |
                    **/DI*
            - run: |
                for file in ${{ steps.changed_dic.outputs.files }}; do
                  # do somethihg..
                  echo "$file"
                done
            - uses: yumemi-inc/changed-files@v3
              id: changed_lbr
              with:
                patterns: |
                    **/LM*
            - run: |
                for file in ${{ steps.changed_lbr.outputs.files }}; do
                  # do somethihg..
                  echo "$file"
                done
            - name: put_src
              if: ${{steps.changed_src.outputs.files}}
              uses: kevinpainchaud/simple-ftp-deploy-action@v1.2.1
              with:
                ftp_host: ${{ secrets.HOST_NAME }}
                ftp_username: ${{ secrets.USER_NAME }}
                ftp_password: ${{ secrets.PASSWORD }}
                local_source_dir: "tandem/SRC"
                dist_target_dir: "tandem/SRC"
                delete: "false"
            - name: put_dic
              if: ${{steps.changed_dic.outputs.files}}
              uses: kevinpainchaud/simple-ftp-deploy-action@v1.2.1
              with:
                ftp_host: ${{ secrets.HOST_NAME }}
                ftp_username: ${{ secrets.USER_NAME }}
                ftp_password: ${{ secrets.PASSWORD }}
                local_source_dir: "tandem/DIC"
                dist_target_dir: "tandem/DIC"
                delete: "false"
            - name: put_lbr
              if: ${{steps.changed_lbr.outputs.files}}
              uses: kevinpainchaud/simple-ftp-deploy-action@v1.2.1
              with:
                ftp_host: ${{ secrets.HOST_NAME }}
                ftp_username: ${{ secrets.USER_NAME }}
                ftp_password: ${{ secrets.PASSWORD }}
                local_source_dir: "tandem/LBR"
                dist_target_dir: "tandem/LBR"
                delete: "false"